#!/usr/local/bin/perl
# get all images into one html
print "<HTML>\n";
print "<TITLE>Images</TITLE>";
print "<BODY>\n";
print "<!-- DO NOT EDIT THIS FILE, EDIT THE PERL FILE CREATING IT -->\n";
print "<h3>Examples</h3>";
my $dir = "./$ARGV[0]/";
opendir(DIR, $dir) or die "wrong dir";
my @files = grep {/.*\.png/} readdir DIR;
close DIR;
foreach my $file (@files) {
	my $file1 = $file;
	$file1 =~ s/\.png//;
	print "<h2> Image example: </h2>  <img src=$dir$file>\n";
	}

print "</BODY>\n";
print "</HTML>\n";
